# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [44]:
# %run initialise.py

#### 1. 导入 PyTorch (★☆☆)

In [45]:
import torch

#### 2. 显示 PyTorch 当前版本 (★☆☆)

In [46]:
print(torch.__version__)

1.4.0


#### 3. 创建一个长度为 10，每个元素值都为 0 的一维 Tensor (★☆☆)

In [47]:
torch.zeros([10])

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. 计算任意 Tensor 的内存占用 (★☆☆)

In [48]:
t = torch.zeros([10,3])
print('%d bytes' % (t.element_size() * t.nelement()))

120 bytes


#### 5. 如何通过命令行获取 PyTorch 函数的帮助文档 (★☆☆)
该问题目前似乎无解。

#### 6. 创建一个长度为 10 的一维 Tensor，除了第五个元素是 1 外，其他元素都是 0(★☆☆)

In [49]:
t = torch.zeros([10])
t[4] = 1
t

tensor([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. 创建一个元素值依次为 10 到 49 的一维 Tensor(★☆☆)

In [50]:
torch.arange(10, 50)

tensor([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
        28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45,
        46, 47, 48, 49])

#### 8. 将一个一维 Tensor 翻转（`[1,2,3]` 变为 `[3,2,1]`）(★☆☆)

In [51]:
t = torch.arange(10, 20)
t.flip(0)

tensor([19, 18, 17, 16, 15, 14, 13, 12, 11, 10])

#### 9. 创建一个 3\*3 的二维 Tensor，值为 0 到 8 (★☆☆)

In [52]:
torch.arange(9).view([3,3])

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

#### 10. 获取 [1,2,0,0,4,0] 中非零元素的下标(★☆☆)

In [53]:
t = torch.Tensor([1,2,0,0,4,0])
t.nonzero()

tensor([[0],
        [1],
        [4]])

#### 11. 创建一个 3\*3 的 单位矩阵（identity matrix） (★☆☆)

In [54]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

#### 12. 创建一个 3x3x3 的随机 Tensor (★☆☆)

In [55]:
torch.rand([3,3,3])

tensor([[[0.3535, 0.6218, 0.2071],
         [0.4987, 0.3297, 0.3077],
         [0.8799, 0.7423, 0.5187]],

        [[0.1057, 0.6544, 0.6071],
         [0.3751, 0.9311, 0.5071],
         [0.7958, 0.1009, 0.9900]],

        [[0.5937, 0.0500, 0.8445],
         [0.2194, 0.5079, 0.4057],
         [0.4983, 0.8374, 0.4039]]])

#### 13. 创建一个 10x10 的随机 Tensor，并找出其中的最大值和最小值(★☆☆)

In [56]:
t = torch.rand([10, 10])
print(t.max())
print(t.min())

tensor(0.9926)
tensor(0.0224)


#### 14. 创建一个长度为 30 的随机一维 Tensor，并计算平均值(★☆☆)

In [57]:
t = torch.rand([30])
t.mean()

tensor(0.4501)

#### 15. 创建一个二维 Tensor，最外围元素是 1，内部元素都是 0 (★☆☆)

In [58]:
t = torch.ones([4,3])
t[1:-1,1:-1] = 0
t

tensor([[1., 1., 1.],
        [1., 0., 1.],
        [1., 0., 1.],
        [1., 1., 1.]])

#### 16. 对一个已有 Tensor 外围添加一圈 0 (★☆☆)

In [59]:
t = torch.ones([2,2])
torch.nn.functional.pad(t, (1,1,1,1), mode='constant', value=0)

tensor([[0., 0., 0., 0.],
        [0., 1., 1., 0.],
        [0., 1., 1., 0.],
        [0., 0., 0., 0.]])

#### 17. 以下代码的运行结果是什么？ (★☆☆)
```python
0 * torch.Tensor([float('NaN')])
torch.Tensor([float('NaN')]) == torch.Tensor([float('NaN')])
torch.Tensor([float('Inf')]) > torch.Tensor([float('NaN')])
torch.Tensor([float('NaN')]) - torch.Tensor([float('NaN')])
torch.Tensor([float('NaN')]) in set([torch.Tensor([float('NaN')])])
0.3 == 3 * 0.1
```

In [60]:
print(0 * torch.Tensor([float('NaN')]))
print(torch.Tensor([float('NaN')]) == torch.Tensor([float('NaN')]))
print(torch.Tensor([float('Inf')]) > torch.Tensor([float('NaN')]))
print(torch.Tensor([float('NaN')]) - torch.Tensor([float('NaN')]))
print(torch.Tensor([float('NaN')]) in set([torch.Tensor([float('NaN')])]))
print(0.3 == 3 * 0.1)

tensor([nan])
tensor([False])
tensor([False])
tensor([nan])
False
False


#### 18. 创建一个 5x5 的矩阵，对角线正下方元素是 1,2,3,4 (★☆☆)

In [61]:
below_diagonal = torch.Tensor([1,2,3,4])
torch.diag(below_diagonal, diagonal=-1)

tensor([[0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0.],
        [0., 2., 0., 0., 0.],
        [0., 0., 3., 0., 0.],
        [0., 0., 0., 4., 0.]])

#### 19. 创建一个 8x8 矩阵，元素值为 0，1 交替出现（类似国际象棋棋盘样式，黑色对应 0，白色对应 1） (★☆☆)

In [62]:
t = torch.zeros((8,8),dtype=int)
t[1::2,::2] = 1
t[::2,1::2] = 1
print(t)

tensor([[0, 1, 0, 1, 0, 1, 0, 1],
        [1, 0, 1, 0, 1, 0, 1, 0],
        [0, 1, 0, 1, 0, 1, 0, 1],
        [1, 0, 1, 0, 1, 0, 1, 0],
        [0, 1, 0, 1, 0, 1, 0, 1],
        [1, 0, 1, 0, 1, 0, 1, 0],
        [0, 1, 0, 1, 0, 1, 0, 1],
        [1, 0, 1, 0, 1, 0, 1, 0]])


#### 20. 一个尺寸为 (6,7,8) 的 Tensor，第 100 个元素的索引（index）是多少？返回的答案应符合 (x,y,z) 格式。
提示：原问题答案使用了 numpy 中的 unravel_index 函数。PyTorch 中暂时没有对应函数，所以需要自己写代码计算。

In [63]:
# 这个函数来自 https://discuss.pytorch.org/t/how-to-do-a-unravel-index-in-pytorch-just-like-in-numpy/12987/3
def unravel_index(index, shape):
    out = []
    for dim in reversed(shape):
        out.append(index % dim)
        index = index // dim
    return tuple(reversed(out))

print(unravel_index(99,(6,7,8)))

(1, 5, 3)


#### 21. 使用 repeat 函数创建一个 8\*8 矩阵，元素值为 0，1 交替出现（类似国际象棋棋盘样式，黑色对应 0，白色对应 1）  (★☆☆)

In [64]:
t = torch.Tensor([[0, 1],
                  [1, 0]])
t.repeat([4, 4])

tensor([[0., 1., 0., 1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1., 0., 1., 0.],
        [0., 1., 0., 1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1., 0., 1., 0.],
        [0., 1., 0., 1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1., 0., 1., 0.],
        [0., 1., 0., 1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 22. 标准化（Normalize）一个 5x5 的随机矩阵 (★☆☆)

In [65]:
t = torch.rand([5,5])
(t - t.mean()) / t.std()

tensor([[-0.7410,  1.7085,  0.4172, -0.7988, -0.3194],
        [-1.1070, -0.3586,  1.3849, -1.1555, -0.4769],
        [ 0.9504, -1.4502,  1.2538,  0.1464, -1.2049],
        [-0.0923,  0.1852, -0.6042,  1.3192,  0.8722],
        [ 1.3516, -1.1981,  1.1526, -1.1021, -0.1329]])

#### 23. 创建一个自定义数据结构，使用 4 个无符号字节定义颜色。
原文：Create a custom dtype that describes a color as four unsigned bytes (RGBA)

没太明白题目……

#### 24. 将一个 5x3 矩阵乘以一个 3x2 矩阵(★☆☆)

In [66]:
a = torch.ones([5,3])
b = torch.ones([3,2])
torch.mm(a,b)

tensor([[3., 3.],
        [3., 3.],
        [3., 3.],
        [3., 3.],
        [3., 3.]])

#### 25. 给定一个一维 Tensor，将其中值在 3-8 之间（不包含 3 和 8）的元素取负（不创建新 Tensor） (★☆☆)

In [67]:
t = torch.arange(10)
t[(3<t) & (t<8)] *= -1
t

tensor([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9])

#### 26.以下代码的输出值是什么？ (★☆☆)
```python
# 作者: Jake VanderPlas

print(sum(range(5),-1))
from torch import *
print(sum(range(5),-1))
```

In [68]:
print(sum(range(5),-1))
def test():
    from torch import sum
    print(sum(torch.arange(5), -1))
test()

9
tensor(10)


#### 27. 给定一个整数向量 Z, 以下哪些式子是合法的? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [69]:
# 被注释掉的都不合法
Z = torch.Tensor([1, 2]).type(torch.int)


Z**Z
# 2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
# Z<Z>Z

tensor([1, 2], dtype=torch.int32)

#### 28. 以下表达式的计算结果分别是什么?
```python
torch.Tensor(0) / torch.Tensor(0)
torch.Tensor(0) // torch.Tensor(0)
torch.Tensor([float('NaN')]).type(torch.int).type(torch.float)
```

In [70]:
print(torch.Tensor(0) / torch.Tensor(0))
print(torch.Tensor(0) // torch.Tensor(0))
print(torch.Tensor([float('NaN')]).type(torch.int).type(torch.float))

tensor([])
tensor([])
tensor([-2.1475e+09])


#### 29. 将 float 类型的 Tensor 中元素进位转换为整数 (★☆☆)
译者注：这里的 "进位" 原文是 round away from zero，即 3.2 => 4，-3.2=> -4。可参考 https://en.wikipedia.org/wiki/Rounding

In [71]:
t = torch.randn([2,3]) * 3
print(t)

torch.mul(torch.sign(t), torch.ceil(torch.abs(t)))

tensor([[-1.4683, -4.8236, -5.8396],
        [-0.4007, -2.2996, -0.9277]])


tensor([[-2., -5., -6.],
        [-1., -3., -1.]])

#### 30. 找出两个一维 Tensor 中都出现的元素 (★☆☆)
译者注：numpy 可以使用 `intersect1d` 函数，但 PyTorch 暂无对应函数。简单的处理方法就是转成 numpy array 后使用 intersect1d。

In [29]:
# 原题答案
import numpy as np
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(Z1)
print(Z2)
print(np.intersect1d(Z1,Z2))

[1 3 1 1 0 6 0 4 5 3]
[1 7 2 3 5 4 5 8 0 1]
[0 1 3 4 5]


#### 31. 如何忽略所有的 PyTorch 警告（warnings） (不建议这么做)? (★☆☆)
译者注：numpy 可直接使用 seterr 方法忽略警告，但是 PyTorch 没有内置的相关设置。但是 PyTorch 的所有警告都是使用了 Python 中内置的 warnings，因此可以直接使用 Python 对 warnings 的操作

In [30]:
import warnings
warnings.filterwarnings("ignore")

#### 32. 以下表达式的值为真吗？ (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

PyTorch 中没有对应 Numpy 的 emath 的模块

In [31]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

#### 33. 如何获取昨天、今天、明天的日期？ (★☆☆)
译者注：PyTorch 中没有关于日期的模块。

In [32]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')

#### 34. 如何获取 2016 年 7 月的每一天日期? (★★☆)
译者注：PyTorch 中没有关于日期的模块。

In [33]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. 在不复制值的情况下做原地计算 ((A+B)*(-A/2))(★★☆)
译者注：计算过程中的值只能保存在 A/B 中，不能创建新的 Tensor

In [34]:
A = torch.ones(3)*1
B = torch.ones(3)*2
torch.add(A, B, out=B)
torch.div(A, 2, out=A)
torch.neg_(A)
torch.mul(A, B, out=B)
B

tensor([-1.5000, -1.5000, -1.5000])

#### 36. 用 5 种不同的方法提取随机 Tensor 中每个元素的整数部分 (★★☆)

In [35]:
Z = torch.rand([2,2]) * 5
print(Z)


print(Z - Z%1)
print(torch.floor(Z))
print(torch.ceil(Z)-1)
print(Z.type(torch.int))
print(torch.trunc(Z))

tensor([[3.6824, 3.8952],
        [4.7558, 0.3342]])
tensor([[3., 3.],
        [4., 0.]])
tensor([[3., 3.],
        [4., 0.]])
tensor([[3., 3.],
        [4., 0.]])
tensor([[3, 3],
        [4, 0]], dtype=torch.int32)
tensor([[3., 3.],
        [4., 0.]])


#### 37. 创建一个 5x5 矩阵，每一行的值是 0-4(★★☆)

In [36]:
torch.arange(5).repeat([5,1])

tensor([[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]])

#### 38. 创建一个生成器函数，用于生成 10 个整数，并用这个生成器函数创建一个一维 Tensor(★☆☆)
译者注:numpy 支持从生成器中创建 array，但 PyTorch 不支持。可以先将这个生成器转换成 numpy array，再转换为 PyTorch tensor

In [37]:
def g():
    yield from range(10)
torch.from_numpy(np.fromiter(g(), dtype=np.int))

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 39. 创建一个长度为 10 的向量，每个元素的值在 0-1 之间（不包括 0 和 1）(★★☆)

In [38]:
torch.linspace(0, 1, steps=12)[1:-1]

tensor([0.0909, 0.1818, 0.2727, 0.3636, 0.4545, 0.5455, 0.6364, 0.7273, 0.8182,
        0.9091])

#### 40. 创建一个长度为 10 的随机向量，并排序(★★☆)

In [39]:
torch.sort(torch.rand([10]))

torch.return_types.sort(values=tensor([0.2024, 0.2088, 0.2191, 0.3271, 0.3837, 0.5384, 0.6871, 0.8495, 0.8641,
        0.8957]), indices=tensor([8, 2, 4, 9, 1, 6, 5, 0, 3, 7]))

#### 41. 对一个小向量求和时，如何计算才能比使用 np.sum 更快？(★★☆)
译者注：在 numpy 中，可以使用 `np.add.reduce`，在小向量上计算速度快于`np.sum`。但 PyTorch 似乎没有对应的方法，经测试，对 `torch.arange(10)` 进行求和时，torch.sum 仍然快于 np.add.reduce

In [40]:
# 原题答案
Z = np.arange(10)
np.add.reduce(Z)

45

#### 42. 给定两个随机 Tensor A 和 B，判断是否相等 (★★☆)

In [41]:
# 检查值是否精确相等
print(torch.equal(torch.Tensor([1.1, 2.1]), torch.Tensor([1, 2])))

# 检查值相等时允许一定误差
print(torch.allclose(torch.Tensor([1.1, 2.1]), torch.Tensor([1, 2]), atol=0.2))

False
True


#### 43. 将 Tensor 转变为只读(★★☆)
译者注：numpy 可以对数组定义 writeable 属性，但 PyTorch 貌似不支持

In [72]:
# 原题答案
Z = np.zeros(10)
Z.flags.writeable = False
# Z[0] = 1

#### 44. 一个随机 10x2 矩阵，每一行表示一个笛卡尔坐标，将其转换为对应的极坐标值 (★★☆)

In [73]:
t = torch.rand([10, 2])
X = t[:,0]
Y = t[:,1]
R = torch.sqrt(X**2+Y**2)
T = torch.atan(Y/X)
torch.stack([R,T], dim=1)

tensor([[1.0625, 1.0960],
        [1.1245, 0.7912],
        [0.8325, 0.0044],
        [1.0051, 0.8870],
        [1.3247, 0.8002],
        [0.6153, 0.6570],
        [0.6864, 0.4895],
        [0.8644, 1.4203],
        [0.4298, 1.3370],
        [0.8034, 0.8322]])

#### 45. 创建一个长度为 10 的随机向量，将其中最大值替换为 0(★★☆)

In [74]:
t = torch.rand(10)
t[torch.argmax(t)] = 0
t

tensor([0.3938, 0.2359, 0.2153, 0.0000, 0.1971, 0.0092, 0.7057, 0.2028, 0.5011,
        0.1906])

#### 46. 在直角坐标轴上 (0,0) 到 (1,1) 区域内放一个 5x5 的网格，创建一个5x5x2 的 Tensor，其值对应网格中每个点的坐标(★★☆)
译者注：原题要求使用 numpy 的 structured array 这个数据结构，PyTorch 疑似没有。故略微修改了题目。

In [75]:
X,Y = torch.meshgrid(torch.linspace(0,1,5),
                     torch.linspace(0,1,5))
torch.stack([X,Y], dim=2)

tensor([[[0.0000, 0.0000],
         [0.0000, 0.2500],
         [0.0000, 0.5000],
         [0.0000, 0.7500],
         [0.0000, 1.0000]],

        [[0.2500, 0.0000],
         [0.2500, 0.2500],
         [0.2500, 0.5000],
         [0.2500, 0.7500],
         [0.2500, 1.0000]],

        [[0.5000, 0.0000],
         [0.5000, 0.2500],
         [0.5000, 0.5000],
         [0.5000, 0.7500],
         [0.5000, 1.0000]],

        [[0.7500, 0.0000],
         [0.7500, 0.2500],
         [0.7500, 0.5000],
         [0.7500, 0.7500],
         [0.7500, 1.0000]],

        [[1.0000, 0.0000],
         [1.0000, 0.2500],
         [1.0000, 0.5000],
         [1.0000, 0.7500],
         [1.0000, 1.0000]]])

#### 47. 给定两个向量 X,Y，创建一个柯西矩阵 C（Cij =1/(xi - yj)）

In [76]:
x = torch.Tensor([1,2,3])
y = torch.Tensor([4,8,12, 15])
torch.div(1, x.view([-1,1]) - y)

tensor([[-0.3333, -0.1429, -0.0909, -0.0714],
        [-0.5000, -0.1667, -0.1000, -0.0769],
        [-1.0000, -0.2000, -0.1111, -0.0833]])

#### 48. 打印 PyTorch Tensor 每一种标量数据结构的最大和最小可表示数（representable value）(★★☆)

In [78]:
for dtype in [torch.int8, torch.int32, torch.int64]:
    print(torch.iinfo(dtype).min)
    print(torch.iinfo(dtype).max)
for dtype in [torch.float32, torch.float64]:
    print(torch.finfo(dtype).min)
    print(torch.finfo(dtype).max)
    print(torch.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028234663852886e+38
3.4028234663852886e+38
1.1920928955078125e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. 如何完整显示 Tensor 的所有值? (★★☆)

In [112]:
torch.set_printoptions(threshold=float('NaN'))
Z = torch.zeros((16,16))
print(Z)

# 恢复默认打印设置
torch.set_printoptions(threshold=1000)

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0

#### 50. 给定一个标量和一个向量，找出向量中与给定标量值最接近的元素(★★☆)

In [113]:
t = torch.rand([5])
print(t)
scalar = 0.123
i = torch.abs(t-scalar).argmin()
print(t[i])

tensor([0.9369, 0.9029, 0.7763, 0.7393, 0.7171])
tensor(0.7171)


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)
译者注：又要使用 Numpy 中的 structured array。PyTorch 似乎没有对应数据结构。跳过本题

#### 52. 给定一个 (100,2) 的矩阵，每行表示一个点的坐标。计算所有点两两之间距离。(★★☆)

In [116]:
# 答案一
t = torch.rand([100,2])
X = t[:,0].view([1,-1])
Y = t[:,1].view([1,-1])
print(torch.sqrt((X-X.T)**2 + (Y-Y.T)**2))


# 答案二（使用 scipy，快很多）
# 感谢 Gavin Heverly-Coulson
import scipy
import scipy.spatial

D = scipy.spatial.distance.cdist(t,t)
print(D)

tensor([[0.0000, 0.1477, 0.3086,  ..., 0.6090, 0.4416, 0.6262],
        [0.1477, 0.0000, 0.1733,  ..., 0.6905, 0.4497, 0.7396],
        [0.3086, 0.1733, 0.0000,  ..., 0.8560, 0.4249, 0.9125],
        ...,
        [0.6090, 0.6905, 0.8560,  ..., 0.0000, 1.0326, 0.1950],
        [0.4416, 0.4497, 0.4249,  ..., 1.0326, 0.0000, 1.0067],
        [0.6262, 0.7396, 0.9125,  ..., 0.1950, 1.0067, 0.0000]])
[[0.         0.14769054 0.30863713 ... 0.60896666 0.44158527 0.62620633]
 [0.14769054 0.         0.17327868 ... 0.69051978 0.44965802 0.73958197]
 [0.30863713 0.17327868 0.         ... 0.85603198 0.42492931 0.91250794]
 ...
 [0.60896666 0.69051978 0.85603198 ... 0.         1.03264791 0.19495208]
 [0.44158527 0.44965802 0.42492931 ... 1.03264791 0.         1.00674365]
 [0.62620633 0.73958197 0.91250794 ... 0.19495208 1.00674365 0.        ]]


#### 53. 原地将一个浮点型 (32 bits) Tensor 转换为整型（32 bits）?
译者注：原题使用了 Numpy 的 `view` 方法，该方法与 PyTorch Tensor 中的 `view` 作用并不相同。以下为原题答案。暂未找到 PyTorch 如何处理这个问题

In [118]:
# Thanks Vikas (https://stackoverflow.com/a/10622758/5989906)
# & unutbu (https://stackoverflow.com/a/4396247/5989906)
Z = (np.random.rand(10)*100).astype(np.float32)
Y = Z.view(np.int32)
Y[:] = Z
print(Y)

[ 5 37 38 85 29 71 53 58  2  2]


#### 54. 将以下内容的 Tensor 保存至硬盘，并再次读取(★★☆)
```
1, 2, 3, 4, 5
6, 0, 0, 7, 8
0, 0, 9,10,11
```
译者注：原题是问“如果读取以下内容的文件”，使用了 numpy 的 `genfromtxt` 方法。由于 PyTorch 不支持从纯文本读取 Tensor，故略微修改了题目

In [122]:
t = torch.Tensor([[1, 2, 3, 4, 5],
                 [6, 0, 0, 7, 8],
                 [0, 0, 9,10,11]])
torch.save(t, '/Users/Desktop/tensors.pt')
s = torch.load('/Users/Desktop/tensors.pt')
s

tensor([[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  0.,  0.,  7.,  8.],
        [ 0.,  0.,  9., 10., 11.]])

#### 55. `enumerate` 函数在 PyTorch 中对应的函数是什么？(★★☆)
译者注：原题是问 numpy 中的对应函数，即 `ndenumerate`。但 PyTorch 中好像没有

In [123]:
# 原题答案
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
print(index, value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)
译者注：这是啥玩意？

In [124]:
# 原题答案
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. 一个矩阵中随机选 p 个元素，并替换成其他值(★★☆)

In [134]:
p = 3
t = torch.zeros([3,3])
indices = torch.from_numpy(np.random.choice(range(9), p))
t.put_(indices, torch.rand(p), accumulate=True)

tensor([[0.0000, 0.7138, 0.0000],
        [0.0000, 0.0000, 0.7391],
        [0.0000, 0.9552, 0.0000]])

#### 58. 给定一个矩阵，计算每个元素减去所在行的平均数(★★☆)

In [140]:
X = torch.arange(10).view([2,5]).type(torch.float32)
Y = X - X.mean(axis=1, keepdims=True)
Y

tensor([[-2., -1.,  0.,  1.,  2.],
        [-2., -1.,  0.,  1.,  2.]])

#### 59. 给定一个矩阵，根据第 n 列的值对行排序(★★☆)

In [147]:
t = torch.randint(0,10,(3,3))
n = 1
print(t)
print(t[t[:,1].argsort()])

tensor([[8, 4, 3],
        [8, 6, 1],
        [1, 4, 8]])
tensor([[8, 4, 3],
        [1, 4, 8],
        [8, 6, 1]])


#### 60. 给定一个矩阵，判断是否存在值全为 0 的列(★★☆)

In [187]:
t = torch.randint(0,3,(3,10))
print(t)
print((t==0).all(dim=0).any)
# print((~t.any(dim=0)).any())

tensor([[0, 2, 0, 1, 0, 0, 2, 2, 0, 1],
        [1, 0, 0, 2, 1, 2, 2, 0, 0, 0],
        [1, 0, 1, 1, 0, 1, 1, 2, 0, 0]])
tensor([False, False, False, False, False, False, False, False,  True, False])


#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)