# 100 PyTorch Tensor exercises

这里有 100 道关于 PyTorch Tensor 的练习题。原题来自于 https://github.com/rougier/numpy-100 ，是关于 Numpy 的练习题。

我将题目翻译成中文，并提供了 PyTorch Tensor 的da'an

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [44]:
# %run initialise.py

#### 1. 导入 PyTorch (★☆☆)

In [15]:
import torch
import numpy as np

#### 2. 显示 PyTorch 当前版本 (★☆☆)

In [46]:
print(torch.__version__)

1.4.0


#### 3. 创建一个长度为 10，每个元素值都为 0 的一维 Tensor (★☆☆)

In [47]:
torch.zeros([10])

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. 计算任意 Tensor 的内存占用 (★☆☆)

In [48]:
t = torch.zeros([10,3])
print('%d bytes' % (t.element_size() * t.nelement()))

120 bytes


#### 5. 如何通过命令行获取 PyTorch 函数的帮助文档 (★☆☆)
该问题目前似乎无解。

#### 6. 创建一个长度为 10 的一维 Tensor，除了第五个元素是 1 外，其他元素都是 0(★☆☆)

In [49]:
t = torch.zeros([10])
t[4] = 1
t

tensor([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. 创建一个元素值依次为 10 到 49 的一维 Tensor(★☆☆)

In [50]:
torch.arange(10, 50)

tensor([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
        28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45,
        46, 47, 48, 49])

#### 8. 将一个一维 Tensor 翻转（`[1,2,3]` 变为 `[3,2,1]`）(★☆☆)

In [51]:
t = torch.arange(10, 20)
t.flip(0)

tensor([19, 18, 17, 16, 15, 14, 13, 12, 11, 10])

#### 9. 创建一个 3\*3 的二维 Tensor，值为 0 到 8 (★☆☆)

In [52]:
torch.arange(9).view([3,3])

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

#### 10. 获取 [1,2,0,0,4,0] 中非零元素的下标(★☆☆)

In [53]:
t = torch.Tensor([1,2,0,0,4,0])
t.nonzero()

tensor([[0],
        [1],
        [4]])

#### 11. 创建一个 3\*3 的 单位矩阵（identity matrix） (★☆☆)

In [54]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

#### 12. 创建一个 3x3x3 的随机 Tensor (★☆☆)

In [55]:
torch.rand([3,3,3])

tensor([[[0.3535, 0.6218, 0.2071],
         [0.4987, 0.3297, 0.3077],
         [0.8799, 0.7423, 0.5187]],

        [[0.1057, 0.6544, 0.6071],
         [0.3751, 0.9311, 0.5071],
         [0.7958, 0.1009, 0.9900]],

        [[0.5937, 0.0500, 0.8445],
         [0.2194, 0.5079, 0.4057],
         [0.4983, 0.8374, 0.4039]]])

#### 13. 创建一个 10x10 的随机 Tensor，并找出其中的最大值和最小值(★☆☆)

In [56]:
t = torch.rand([10, 10])
print(t.max())
print(t.min())

tensor(0.9926)
tensor(0.0224)


#### 14. 创建一个长度为 30 的随机一维 Tensor，并计算平均值(★☆☆)

In [57]:
t = torch.rand([30])
t.mean()

tensor(0.4501)

#### 15. 创建一个二维 Tensor，最外围元素是 1，内部元素都是 0 (★☆☆)

In [58]:
t = torch.ones([4,3])
t[1:-1,1:-1] = 0
t

tensor([[1., 1., 1.],
        [1., 0., 1.],
        [1., 0., 1.],
        [1., 1., 1.]])

#### 16. 对一个已有 Tensor 外围添加一圈 0 (★☆☆)

In [59]:
t = torch.ones([2,2])
torch.nn.functional.pad(t, (1,1,1,1), mode='constant', value=0)

tensor([[0., 0., 0., 0.],
        [0., 1., 1., 0.],
        [0., 1., 1., 0.],
        [0., 0., 0., 0.]])

#### 17. 以下代码的运行结果是什么？ (★☆☆)
```python
0 * torch.Tensor([float('NaN')])
torch.Tensor([float('NaN')]) == torch.Tensor([float('NaN')])
torch.Tensor([float('Inf')]) > torch.Tensor([float('NaN')])
torch.Tensor([float('NaN')]) - torch.Tensor([float('NaN')])
torch.Tensor([float('NaN')]) in set([torch.Tensor([float('NaN')])])
0.3 == 3 * 0.1
```

In [60]:
print(0 * torch.Tensor([float('NaN')]))
print(torch.Tensor([float('NaN')]) == torch.Tensor([float('NaN')]))
print(torch.Tensor([float('Inf')]) > torch.Tensor([float('NaN')]))
print(torch.Tensor([float('NaN')]) - torch.Tensor([float('NaN')]))
print(torch.Tensor([float('NaN')]) in set([torch.Tensor([float('NaN')])]))
print(0.3 == 3 * 0.1)

tensor([nan])
tensor([False])
tensor([False])
tensor([nan])
False
False


#### 18. 创建一个 5x5 的矩阵，对角线正下方元素是 1,2,3,4 (★☆☆)

In [61]:
below_diagonal = torch.Tensor([1,2,3,4])
torch.diag(below_diagonal, diagonal=-1)

tensor([[0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0.],
        [0., 2., 0., 0., 0.],
        [0., 0., 3., 0., 0.],
        [0., 0., 0., 4., 0.]])

#### 19. 创建一个 8x8 矩阵，元素值为 0，1 交替出现（类似国际象棋棋盘样式，黑色对应 0，白色对应 1） (★☆☆)

In [62]:
t = torch.zeros((8,8),dtype=int)
t[1::2,::2] = 1
t[::2,1::2] = 1
print(t)

tensor([[0, 1, 0, 1, 0, 1, 0, 1],
        [1, 0, 1, 0, 1, 0, 1, 0],
        [0, 1, 0, 1, 0, 1, 0, 1],
        [1, 0, 1, 0, 1, 0, 1, 0],
        [0, 1, 0, 1, 0, 1, 0, 1],
        [1, 0, 1, 0, 1, 0, 1, 0],
        [0, 1, 0, 1, 0, 1, 0, 1],
        [1, 0, 1, 0, 1, 0, 1, 0]])


#### 20. 一个尺寸为 (6,7,8) 的 Tensor，第 100 个元素的索引（index）是多少？返回的答案应符合 (x,y,z) 格式。
提示：原问题答案使用了 numpy 中的 unravel_index 函数。PyTorch 中暂时没有对应函数，所以需要自己写代码计算。

In [63]:
# 这个函数来自 https://discuss.pytorch.org/t/how-to-do-a-unravel-index-in-pytorch-just-like-in-numpy/12987/3
def unravel_index(index, shape):
    out = []
    for dim in reversed(shape):
        out.append(index % dim)
        index = index // dim
    return tuple(reversed(out))

print(unravel_index(99,(6,7,8)))

(1, 5, 3)


#### 21. 使用 repeat 函数创建一个 8\*8 矩阵，元素值为 0，1 交替出现（类似国际象棋棋盘样式，黑色对应 0，白色对应 1）  (★☆☆)

In [64]:
t = torch.Tensor([[0, 1],
                  [1, 0]])
t.repeat([4, 4])

tensor([[0., 1., 0., 1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1., 0., 1., 0.],
        [0., 1., 0., 1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1., 0., 1., 0.],
        [0., 1., 0., 1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1., 0., 1., 0.],
        [0., 1., 0., 1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 22. 标准化（Normalize）一个 5x5 的随机矩阵 (★☆☆)

In [65]:
t = torch.rand([5,5])
(t - t.mean()) / t.std()

tensor([[-0.7410,  1.7085,  0.4172, -0.7988, -0.3194],
        [-1.1070, -0.3586,  1.3849, -1.1555, -0.4769],
        [ 0.9504, -1.4502,  1.2538,  0.1464, -1.2049],
        [-0.0923,  0.1852, -0.6042,  1.3192,  0.8722],
        [ 1.3516, -1.1981,  1.1526, -1.1021, -0.1329]])

#### 23. 创建一个自定义数据结构，使用 4 个无符号字节定义颜色。
原文：Create a custom dtype that describes a color as four unsigned bytes (RGBA)

没太明白题目……

#### 24. 将一个 5x3 矩阵乘以一个 3x2 矩阵(★☆☆)

In [66]:
a = torch.ones([5,3])
b = torch.ones([3,2])
torch.mm(a,b)

tensor([[3., 3.],
        [3., 3.],
        [3., 3.],
        [3., 3.],
        [3., 3.]])

#### 25. 给定一个一维 Tensor，将其中值在 3-8 之间（不包含 3 和 8）的元素取负（不创建新 Tensor） (★☆☆)

In [67]:
t = torch.arange(10)
t[(3<t) & (t<8)] *= -1
t

tensor([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9])

#### 26.以下代码的输出值是什么？ (★☆☆)
```python
# 作者: Jake VanderPlas

print(sum(range(5),-1))
from torch import *
print(sum(range(5),-1))
```

In [68]:
print(sum(range(5),-1))
def test():
    from torch import sum
    print(sum(torch.arange(5), -1))
test()

9
tensor(10)


#### 27. 给定一个整数向量 Z, 以下哪些式子是合法的? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [69]:
# 被注释掉的都不合法
Z = torch.Tensor([1, 2]).type(torch.int)


Z**Z
# 2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
# Z<Z>Z

tensor([1, 2], dtype=torch.int32)

#### 28. 以下表达式的计算结果分别是什么?
```python
torch.Tensor(0) / torch.Tensor(0)
torch.Tensor(0) // torch.Tensor(0)
torch.Tensor([float('NaN')]).type(torch.int).type(torch.float)
```

In [70]:
print(torch.Tensor(0) / torch.Tensor(0))
print(torch.Tensor(0) // torch.Tensor(0))
print(torch.Tensor([float('NaN')]).type(torch.int).type(torch.float))

tensor([])
tensor([])
tensor([-2.1475e+09])


#### 29. 将 float 类型的 Tensor 中元素进位转换为整数 (★☆☆)
译者注：这里的 "进位" 原文是 round away from zero，即 3.2 => 4，-3.2=> -4。可参考 https://en.wikipedia.org/wiki/Rounding

In [71]:
t = torch.randn([2,3]) * 3
print(t)

torch.mul(torch.sign(t), torch.ceil(torch.abs(t)))

tensor([[-1.4683, -4.8236, -5.8396],
        [-0.4007, -2.2996, -0.9277]])


tensor([[-2., -5., -6.],
        [-1., -3., -1.]])

#### 30. 找出两个一维 Tensor 中都出现的元素 (★☆☆)
译者注：numpy 可以使用 `intersect1d` 函数，但 PyTorch 暂无对应函数。简单的处理方法就是转成 numpy array 后使用 intersect1d。

In [29]:
# 原题答案
import numpy as np
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(Z1)
print(Z2)
print(np.intersect1d(Z1,Z2))

[1 3 1 1 0 6 0 4 5 3]
[1 7 2 3 5 4 5 8 0 1]
[0 1 3 4 5]


#### 31. 如何忽略所有的 PyTorch 警告（warnings） (不建议这么做)? (★☆☆)
译者注：numpy 可直接使用 seterr 方法忽略警告，但是 PyTorch 没有内置的相关设置。但是 PyTorch 的所有警告都是使用了 Python 中内置的 warnings，因此可以直接使用 Python 对 warnings 的操作

In [30]:
import warnings
warnings.filterwarnings("ignore")

#### 32. 以下表达式的值为真吗？ (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

PyTorch 中没有对应 Numpy 的 emath 的模块

In [31]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

#### 33. 如何获取昨天、今天、明天的日期？ (★☆☆)
译者注：PyTorch 中没有关于日期的模块。

In [32]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')

#### 34. 如何获取 2016 年 7 月的每一天日期? (★★☆)
译者注：PyTorch 中没有关于日期的模块。

In [33]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. 在不复制值的情况下做原地计算 ((A+B)*(-A/2))(★★☆)
译者注：计算过程中的值只能保存在 A/B 中，不能创建新的 Tensor

In [34]:
A = torch.ones(3)*1
B = torch.ones(3)*2
torch.add(A, B, out=B)
torch.div(A, 2, out=A)
torch.neg_(A)
torch.mul(A, B, out=B)
B

tensor([-1.5000, -1.5000, -1.5000])

#### 36. 用 5 种不同的方法提取随机 Tensor 中每个元素的整数部分 (★★☆)

In [35]:
Z = torch.rand([2,2]) * 5
print(Z)


print(Z - Z%1)
print(torch.floor(Z))
print(torch.ceil(Z)-1)
print(Z.type(torch.int))
print(torch.trunc(Z))

tensor([[3.6824, 3.8952],
        [4.7558, 0.3342]])
tensor([[3., 3.],
        [4., 0.]])
tensor([[3., 3.],
        [4., 0.]])
tensor([[3., 3.],
        [4., 0.]])
tensor([[3, 3],
        [4, 0]], dtype=torch.int32)
tensor([[3., 3.],
        [4., 0.]])


#### 37. 创建一个 5x5 矩阵，每一行的值是 0-4(★★☆)

In [36]:
torch.arange(5).repeat([5,1])

tensor([[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]])

#### 38. 创建一个生成器函数，用于生成 10 个整数，并用这个生成器函数创建一个一维 Tensor(★☆☆)
译者注:numpy 支持从生成器中创建 array，但 PyTorch 不支持。可以先将这个生成器转换成 numpy array，再转换为 PyTorch tensor

In [37]:
def g():
    yield from range(10)
torch.from_numpy(np.fromiter(g(), dtype=np.int))

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 39. 创建一个长度为 10 的向量，每个元素的值在 0-1 之间（不包括 0 和 1）(★★☆)

In [38]:
torch.linspace(0, 1, steps=12)[1:-1]

tensor([0.0909, 0.1818, 0.2727, 0.3636, 0.4545, 0.5455, 0.6364, 0.7273, 0.8182,
        0.9091])

#### 40. 创建一个长度为 10 的随机向量，并排序(★★☆)

In [39]:
torch.sort(torch.rand([10]))

torch.return_types.sort(values=tensor([0.2024, 0.2088, 0.2191, 0.3271, 0.3837, 0.5384, 0.6871, 0.8495, 0.8641,
        0.8957]), indices=tensor([8, 2, 4, 9, 1, 6, 5, 0, 3, 7]))

#### 41. 对一个小向量求和时，如何计算才能比使用 np.sum 更快？(★★☆)
译者注：在 numpy 中，可以使用 `np.add.reduce`，在小向量上计算速度快于`np.sum`。但 PyTorch 似乎没有对应的方法，经测试，对 `torch.arange(10)` 进行求和时，torch.sum 仍然快于 np.add.reduce

In [40]:
# 原题答案
Z = np.arange(10)
np.add.reduce(Z)

45

#### 42. 给定两个随机 Tensor A 和 B，判断是否相等 (★★☆)

In [41]:
# 检查值是否精确相等
print(torch.equal(torch.Tensor([1.1, 2.1]), torch.Tensor([1, 2])))

# 检查值相等时允许一定误差
print(torch.allclose(torch.Tensor([1.1, 2.1]), torch.Tensor([1, 2]), atol=0.2))

False
True


#### 43. 将 Tensor 转变为只读(★★☆)
译者注：numpy 可以对数组定义 writeable 属性，但 PyTorch 貌似不支持

In [72]:
# 原题答案
Z = np.zeros(10)
Z.flags.writeable = False
# Z[0] = 1

#### 44. 一个随机 10x2 矩阵，每一行表示一个笛卡尔坐标，将其转换为对应的极坐标值 (★★☆)

In [73]:
t = torch.rand([10, 2])
X = t[:,0]
Y = t[:,1]
R = torch.sqrt(X**2+Y**2)
T = torch.atan(Y/X)
torch.stack([R,T], dim=1)

tensor([[1.0625, 1.0960],
        [1.1245, 0.7912],
        [0.8325, 0.0044],
        [1.0051, 0.8870],
        [1.3247, 0.8002],
        [0.6153, 0.6570],
        [0.6864, 0.4895],
        [0.8644, 1.4203],
        [0.4298, 1.3370],
        [0.8034, 0.8322]])

#### 45. 创建一个长度为 10 的随机向量，将其中最大值替换为 0(★★☆)

In [74]:
t = torch.rand(10)
t[torch.argmax(t)] = 0
t

tensor([0.3938, 0.2359, 0.2153, 0.0000, 0.1971, 0.0092, 0.7057, 0.2028, 0.5011,
        0.1906])

#### 46. 在直角坐标轴上 (0,0) 到 (1,1) 区域内放一个 5x5 的网格，创建一个5x5x2 的 Tensor，其值对应网格中每个点的坐标(★★☆)
译者注：原题要求使用 numpy 的 structured array 这个数据结构，PyTorch 疑似没有。故略微修改了题目。

In [75]:
X,Y = torch.meshgrid(torch.linspace(0,1,5),
                     torch.linspace(0,1,5))
torch.stack([X,Y], dim=2)

tensor([[[0.0000, 0.0000],
         [0.0000, 0.2500],
         [0.0000, 0.5000],
         [0.0000, 0.7500],
         [0.0000, 1.0000]],

        [[0.2500, 0.0000],
         [0.2500, 0.2500],
         [0.2500, 0.5000],
         [0.2500, 0.7500],
         [0.2500, 1.0000]],

        [[0.5000, 0.0000],
         [0.5000, 0.2500],
         [0.5000, 0.5000],
         [0.5000, 0.7500],
         [0.5000, 1.0000]],

        [[0.7500, 0.0000],
         [0.7500, 0.2500],
         [0.7500, 0.5000],
         [0.7500, 0.7500],
         [0.7500, 1.0000]],

        [[1.0000, 0.0000],
         [1.0000, 0.2500],
         [1.0000, 0.5000],
         [1.0000, 0.7500],
         [1.0000, 1.0000]]])

#### 47. 给定两个向量 X,Y，创建一个柯西矩阵 C（Cij =1/(xi - yj)）

In [76]:
x = torch.Tensor([1,2,3])
y = torch.Tensor([4,8,12, 15])
torch.div(1, x.view([-1,1]) - y)

tensor([[-0.3333, -0.1429, -0.0909, -0.0714],
        [-0.5000, -0.1667, -0.1000, -0.0769],
        [-1.0000, -0.2000, -0.1111, -0.0833]])

#### 48. 打印 PyTorch Tensor 每一种标量数据结构的最大和最小可表示数（representable value）(★★☆)

In [78]:
for dtype in [torch.int8, torch.int32, torch.int64]:
    print(torch.iinfo(dtype).min)
    print(torch.iinfo(dtype).max)
for dtype in [torch.float32, torch.float64]:
    print(torch.finfo(dtype).min)
    print(torch.finfo(dtype).max)
    print(torch.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028234663852886e+38
3.4028234663852886e+38
1.1920928955078125e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. 如何完整显示 Tensor 的所有值? (★★☆)

In [112]:
torch.set_printoptions(threshold=float('NaN'))
Z = torch.zeros((16,16))
print(Z)

# 恢复默认打印设置
torch.set_printoptions(threshold=1000)

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0

#### 50. 给定一个标量和一个向量，找出向量中与给定标量值最接近的元素(★★☆)

In [113]:
t = torch.rand([5])
print(t)
scalar = 0.123
i = torch.abs(t-scalar).argmin()
print(t[i])

tensor([0.9369, 0.9029, 0.7763, 0.7393, 0.7171])
tensor(0.7171)


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)
译者注：又要使用 Numpy 中的 structured array。PyTorch 似乎没有对应数据结构。跳过本题

#### 52. 给定一个 (100,2) 的矩阵，每行表示一个点的坐标。计算所有点两两之间距离。(★★☆)

In [116]:
# 答案一
t = torch.rand([100,2])
X = t[:,0].view([1,-1])
Y = t[:,1].view([1,-1])
print(torch.sqrt((X-X.T)**2 + (Y-Y.T)**2))


# 答案二（使用 scipy，快很多）
# 感谢 Gavin Heverly-Coulson
import scipy
import scipy.spatial

D = scipy.spatial.distance.cdist(t,t)
print(D)

tensor([[0.0000, 0.1477, 0.3086,  ..., 0.6090, 0.4416, 0.6262],
        [0.1477, 0.0000, 0.1733,  ..., 0.6905, 0.4497, 0.7396],
        [0.3086, 0.1733, 0.0000,  ..., 0.8560, 0.4249, 0.9125],
        ...,
        [0.6090, 0.6905, 0.8560,  ..., 0.0000, 1.0326, 0.1950],
        [0.4416, 0.4497, 0.4249,  ..., 1.0326, 0.0000, 1.0067],
        [0.6262, 0.7396, 0.9125,  ..., 0.1950, 1.0067, 0.0000]])
[[0.         0.14769054 0.30863713 ... 0.60896666 0.44158527 0.62620633]
 [0.14769054 0.         0.17327868 ... 0.69051978 0.44965802 0.73958197]
 [0.30863713 0.17327868 0.         ... 0.85603198 0.42492931 0.91250794]
 ...
 [0.60896666 0.69051978 0.85603198 ... 0.         1.03264791 0.19495208]
 [0.44158527 0.44965802 0.42492931 ... 1.03264791 0.         1.00674365]
 [0.62620633 0.73958197 0.91250794 ... 0.19495208 1.00674365 0.        ]]


#### 53. 原地将一个浮点型 (32 bits) Tensor 转换为整型（32 bits）?
译者注：原题使用了 Numpy 的 `view` 方法，该方法与 PyTorch Tensor 中的 `view` 作用并不相同。以下为原题答案。暂未找到 PyTorch 如何处理这个问题

In [118]:
# Thanks Vikas (https://stackoverflow.com/a/10622758/5989906)
# & unutbu (https://stackoverflow.com/a/4396247/5989906)
Z = (np.random.rand(10)*100).astype(np.float32)
Y = Z.view(np.int32)
Y[:] = Z
print(Y)

[ 5 37 38 85 29 71 53 58  2  2]


#### 54. 将以下内容的 Tensor 保存至硬盘，并再次读取(★★☆)
```
1, 2, 3, 4, 5
6, 0, 0, 7, 8
0, 0, 9,10,11
```
译者注：原题是问“如果读取以下内容的文件”，使用了 numpy 的 `genfromtxt` 方法。由于 PyTorch 不支持从纯文本读取 Tensor，故略微修改了题目

In [122]:
t = torch.Tensor([[1, 2, 3, 4, 5],
                 [6, 0, 0, 7, 8],
                 [0, 0, 9,10,11]])
torch.save(t, '/Users/Desktop/tensors.pt')
s = torch.load('/Users/Desktop/tensors.pt')
s

tensor([[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  0.,  0.,  7.,  8.],
        [ 0.,  0.,  9., 10., 11.]])

#### 55. `enumerate` 函数在 PyTorch 中对应的函数是什么？(★★☆)
译者注：原题是问 numpy 中的对应函数，即 `ndenumerate`。但 PyTorch 中好像没有

In [123]:
# 原题答案
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
print(index, value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)
译者注：这是啥玩意？

In [124]:
# 原题答案
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. 一个矩阵中随机选 p 个元素，并替换成其他值(★★☆)

In [134]:
p = 3
t = torch.zeros([3,3])
indices = torch.from_numpy(np.random.choice(range(9), p))
t.put_(indices, torch.rand(p), accumulate=True)

tensor([[0.0000, 0.7138, 0.0000],
        [0.0000, 0.0000, 0.7391],
        [0.0000, 0.9552, 0.0000]])

#### 58. 给定一个矩阵，计算每个元素减去所在行的平均数(★★☆)

In [140]:
X = torch.arange(10).view([2,5]).type(torch.float32)
Y = X - X.mean(axis=1, keepdims=True)
Y

tensor([[-2., -1.,  0.,  1.,  2.],
        [-2., -1.,  0.,  1.,  2.]])

#### 59. 给定一个矩阵，根据第 n 列的值对行排序(★★☆)

In [147]:
t = torch.randint(0,10,(3,3))
n = 1
print(t)
print(t[t[:,1].argsort()])

tensor([[8, 4, 3],
        [8, 6, 1],
        [1, 4, 8]])
tensor([[8, 4, 3],
        [1, 4, 8],
        [8, 6, 1]])


#### 60. 给定一个矩阵，判断是否存在值全为 0 的列(★★☆)

In [194]:
t = torch.randint(0,3,(3,10))
print(t)
print((t==0).all(dim=0).any().item())

tensor([[1, 0, 0, 0, 0, 2, 1, 2, 0, 2],
        [0, 1, 0, 1, 2, 1, 0, 0, 0, 1],
        [1, 1, 2, 2, 2, 0, 1, 2, 0, 1]])
True


#### 61. 题同 50.(★★☆)

#### 62. 给定两个矩阵，尺寸分别为 (1,3) 和 (3,1)。计算两个矩阵元素两两之和，得到一个 (3,3) 矩阵(★★☆)
译者注：根据题目答案，修改了题目表述。

In [200]:
A = torch.arange(3).view([3,1])
B = torch.arange(3).view([1,3])
A + B

tensor([[0, 1, 2],
        [1, 2, 3],
        [2, 3, 4]])

#### 63. 创建一个继承自 PyTorch.Tensor 的类，并赋予其 name_ 属性 (★★☆)
答案参考：https://discuss.pytorch.org/t/subclassing-torch-tensor/23754/2

In [207]:
class NamedTensor(torch.Tensor):
    @staticmethod
    def __new__(cls, x, name, *args, **kwargs):
        obj = super().__new__(cls, x, *args, **kwargs)
        obj.name_ = name
        return obj

Z = NamedTensor(torch.rand([3,3]), "some_name")
Z.name_

'some_name'

#### 64. 给定一个向量 A，另一个向量 B 中的值为 A 的元素索引。将 B 中索引对应的 A 的元素加 1。（注意 B 中可能有重复的索引，重复几次就要加几次 1）(★★★)
译者注：例如 `A=[1, 1, 1]`, `B=[1,2,2,2]`,则最终的效果是得到向量 `[1,2,4]`，A 中的第一个元素（从 0 开始计数元素）加了一次 1，第二个元素加了 3 次 1

In [226]:
A = torch.Tensor([1,1,1])
B = torch.Tensor([1,2,2,2]).type(torch.int64)
A.index_add(0, B, torch.ones([B.shape[0]]))

tensor([1., 2., 4.])

#### 65. 去研究下 torch.bincount 函数
译者注：原问题的表述真的很难懂，实际上就是用了个 `bincount` 函数。这个函数用法不难，但是三言两语很难说清楚。大家看文档吧

In [231]:
X = torch.Tensor([1,2,3,4,5,6]).type(torch.int64)
I = torch.Tensor([1,3,9,3,4,1]).type(torch.int64)
F = torch.bincount(I,X)
print(F)

tensor([0., 7., 0., 6., 5., 0., 0., 0., 0., 3.], dtype=torch.float64)


#### 66. 给定一个尺寸为 (w,h,3) 的图像，计算图像中有多少种不重复的颜色(★★★)

In [253]:
w,h = 16,16
I = torch.randint(0,256,(h,w,3)).type(torch.int8)
F = I[...,0]*256*256 + I[...,1]*256 +I[...,2]
n = len(torch.unique(F))
n

166

#### 67. 给定一个四维 Tensor，如何计算最后两维的和(★★★)

In [259]:
A = torch.randint(0,10,(3,4,3,4))
A.sum(axis=(-2,-1))

tensor([[49, 44, 47, 61],
        [51, 64, 68, 78],
        [35, 49, 62, 51]])

#### 68. 给定向量 D 以及另一个同长度向量 S。计算 S 中所有值相同元素对应的同位置 D 中的元素的平均数(★★★)
译者注：例如 `D=[1, 1, 0, 1, 0]`, `S=[2, 0, 3, 2, 2]`

S 中值为 `2` 的 3 个元素所在位置对应的 D 中同位置元素是 `[1,1,0]`，平均数是 $2/3$；

同理， S 中值为 `0` 的 1 个元素所在位置对应的 D 中同位置元素是 `[1]`，平均数就是 1

同理， S 中值为 `3` 的 1 个元素所在位置对应的 D 中同位置元素是 `[0]`，平均数就是 0

最终的输出就是 `[1, 2/3， 0]`

In [273]:
# 作者: Jaime Fernández del Río
D = torch.rand([100])
S = torch.randint(0,10,[100])
D_sums = torch.bincount(S, weights=D)
D_counts = torch.bincount(S)
D_means = D_sums / D_counts
print(D_means)

# 也可以使用 Pandas
import pandas as pd
print(pd.Series(D.numpy()).groupby(S.numpy()).mean())

tensor([0.5796, 0.6110, 0.5940, 0.6478, 0.3952, 0.5396, 0.5413, 0.6328, 0.4466,
        0.5895])
0    0.579558
1    0.611022
2    0.594034
3    0.647782
4    0.395194
5    0.539622
6    0.541287
7    0.632786
8    0.446596
9    0.589531
dtype: float32


#### 69. 如何获取两个矩阵相乘的结果的对角线元素? (★★★)

In [285]:
A = torch.arange(4).view([2,2])
B = torch.arange(4).view([2,2])

# 答案一
print(torch.diagonal(torch.mm(A,B)))

# 答案二
print(torch.sum(A * B.T, axis=1))

# 答案三
print(torch.einsum("ij,ji->i", A, B))

tensor([ 2, 11])
tensor([ 2, 11])
tensor([ 2, 11])


#### 70. 给定向量 `[1, 2, 3, 4, 5]`，所有元素之间插入 3 个 0，得到新向量 `[1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5]`(★★★)

In [289]:
t = torch.Tensor([1,2,3,4,5])
t0 = torch.zeros([len(Z) + (len(Z)-1)*3])
t0[::4] = t
t0

tensor([1., 0., 0., 0., 2., 0., 0., 0., 3., 0., 0., 0., 4., 0., 0., 0., 5.])

#### 71. 给定一个尺寸为 (5,5,3) 的 Tensor，如何将它和一个尺寸为 (5,5) 的 Tensor 相乘? (★★★)

In [293]:
A = torch.ones((5,5,3))
B = 2*torch.ones((5,5))
A * B[:,:,None]

tensor([[[2., 2., 2.],
         [2., 2., 2.],
         [2., 2., 2.],
         [2., 2., 2.],
         [2., 2., 2.]],

        [[2., 2., 2.],
         [2., 2., 2.],
         [2., 2., 2.],
         [2., 2., 2.],
         [2., 2., 2.]],

        [[2., 2., 2.],
         [2., 2., 2.],
         [2., 2., 2.],
         [2., 2., 2.],
         [2., 2., 2.]],

        [[2., 2., 2.],
         [2., 2., 2.],
         [2., 2., 2.],
         [2., 2., 2.],
         [2., 2., 2.]],

        [[2., 2., 2.],
         [2., 2., 2.],
         [2., 2., 2.],
         [2., 2., 2.],
         [2., 2., 2.]]])

#### 72. 交换一个 Tensor 内两行的位置? (★★★)

In [294]:
# 作者: Eelco Hoogendoorn
A =  torch.arange(25).view(5,5)
A[[0,1]] = A[[1,0]]
print(A)

tensor([[ 5,  6,  7,  8,  9],
        [ 0,  1,  2,  3,  4],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]])


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)
译者注：看不懂题目到底想干啥……答案给的示例中，有些数据都无法组成三角形（不满足两边之长必须大于第三边）

In [302]:
# 原题答案
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 6, 19) ( 6, 54) (15, 20) (15, 31) (19, 32) (19, 54) (19, 71) (20, 31)
 (21, 47) (21, 77) (24, 55) (24, 64) (28, 31) (28, 78) (31, 38) (31, 76)
 (31, 78) (32, 71) (37, 68) (37, 90) (38, 76) (44, 49) (44, 73) (47, 53)
 (47, 77) (47, 79) (49, 73) (53, 79) (55, 64) (68, 90)]


#### 74. 给定向量 C 是 `bincount` 函数的运行结果，如何计算出向量 A，使得 `torch.bincount(A) == C`?(★★★)

In [307]:
# 作者: Jaime Fernández del Río
t = torch.Tensor([1,1,2,3,4,4,6]).type(torch.int64)
C =  torch.bincount(t)
T = torch.repeat_interleave(torch.arange(len(C)), C)
print(T)

tensor([1, 1, 2, 3, 4, 4, 6])


#### 75. 计算一个一维 Tensor 每个滑动窗口（sliding window）内的平均数 (★★★)

In [328]:
# 作者: Jaime Fernández del Río
def moving_average(a, n=3) :
    ret = torch.cumsum(a, dim=0)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = torch.arange(20)
print(moving_average(Z, n=3))

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18])


#### 76. 给定一个一维 Tensor Z，创建一个二维 Tensor，其第一行是 (Z[0],Z[1],Z[2])，其后的每一行是上一行再后延 1 位（第二行就是 (Z[1],Z[2],Z[3])，最后一行就是 (Z[-3],Z[-2],Z[-1])）(★★★)
译者注：原题使用了 `numpy.lib` 中的 `stride_tricks.as_strided`。PyTorch 有对应函数 `torch.as_strided`但是用法似乎和 numpy 中的用法不太一样，

In [63]:
# 原题答案
# 作者: Joe Kington / Erik Rigtorp
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)

Z = rolling(np.arange(10), 3)
print(Z)

# 对应 PyTorch 版本，会报错
# def rolling(a, window):
#     shape = (a.size()[0] - window + 1, window)
#     strides = (a.element_size(), a.element_size())
#     return torch.as_strided(a, size=shape, stride=strides)
# Z = rolling(torch.arange(10), 3)
# print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. 如何原地对布尔值取反，或改变浮点型数据的正负? (★★★)

In [385]:
Z = torch.randint(0,2,[100])
torch.logical_not(Z, out=Z)

Z = torch.rand([100])
torch.neg(Z, out=Z)

tensor([-0.2840, -0.8931, -0.5477, -0.7215, -0.2820, -0.9569, -0.9097, -0.9031,
        -0.2542, -0.9451, -0.9212, -0.6158, -0.9553, -0.5441, -0.4852, -0.2866,
        -0.3331, -0.6023, -0.8154, -0.6689, -0.4746, -0.1201, -0.8943, -0.9739,
        -0.1949, -0.7605, -0.7338, -0.1762, -0.6662, -0.1584, -0.3059, -0.3109,
        -0.0514, -0.4306, -0.9005, -0.9735, -0.3369, -0.0975, -0.8937, -0.4418,
        -0.6114, -0.8907, -0.4427, -0.8724, -0.5632, -0.0595, -0.8335, -0.3437,
        -0.4713, -0.8920, -0.4929, -0.6631, -0.8832, -0.1838, -0.7656, -0.4362,
        -0.5145, -0.9621, -0.9753, -0.2228, -0.8827, -0.5216, -0.3937, -0.0318,
        -0.9728, -0.4865, -0.0342, -0.0086, -0.6342, -0.9507, -0.6297, -0.2634,
        -0.3199, -0.5835, -0.6927, -0.7704, -0.2197, -0.9681, -0.5293, -0.6745,
        -0.0226, -0.6046, -0.9474, -0.8368, -0.0099, -0.4902, -0.7092, -0.8561,
        -0.9838, -0.4841, -0.6651, -0.9477, -0.2883, -0.7081, -0.6784, -0.0863,
        -0.7160, -0.3286, -0.2335, -0.90

#### 78. P0 和 P1 是两个矩阵，每个矩阵每一行对应一个点的坐标。给定点 p，计算 p 到每一条 (P0[i],P1[i]) 组成的线的距离(★★★)

In [4]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape([len(U),1])
    D = P0 + U*T - p
    return torch.sqrt((D**2).sum(axis=1))


P0 = (torch.rand([10,2])-0.5) * 20
P1 = (torch.rand([10,2])-0.5) * 20
p = (torch.rand([1,2])-0.5) * 20
print(distance(P0, P1, p))

tensor([ 2.1073,  4.5128,  8.9656, 10.6194,  5.6808,  4.5276,  4.4780,  4.6085,
         8.6444,  8.9815])


#### 79. P0， P1 和 P 是三个矩阵，每个矩阵每一行对应一个点的坐标。计算 P 中每一个点到每一条 (P0[i],P1[i]) 组成的线的距离(★★★) (★★★)

In [18]:
# 作者: Italmassov Kuanysh

# 使用了上一题中的 disntance 函数
P0 = (torch.rand([10,2])-0.5) * 20
P1 = (torch.rand([10,2])-0.5) * 20
p = (torch.rand([10,2])-0.5) * 20

print(torch.stack([distance(P0,P1,p_i) for p_i in p]))

tensor([[12.2779,  1.3336,  5.9773,  3.7629,  0.8507, 10.8187,  9.2593,  5.2411,
          9.8643, 10.8570],
        [ 0.9368,  0.6516,  5.8760,  3.3524,  0.9357, 13.7890, 10.2336,  1.3867,
          7.0634,  2.1478],
        [ 7.2894,  2.5639,  2.5726,  1.6594,  1.0776,  9.9672,  7.6524,  2.0011,
          6.9566,  6.2781],
        [ 9.7857,  2.2749,  0.6442,  6.5725,  3.8338, 14.7259, 12.5430,  6.7235,
         11.7759,  6.2779],
        [ 3.2030,  3.7205,  6.4881,  6.6023,  4.1572, 16.7508, 13.3924,  4.7016,
         10.3838,  1.4298],
        [ 3.5490,  4.7498,  5.2435,  2.4653,  4.8120,  8.6169,  4.6326,  4.6806,
          1.0271,  3.9346],
        [ 7.5157,  2.3759,  2.6134,  1.8757,  0.8666, 10.1414,  7.8532,  2.2451,
          7.1938,  6.4142],
        [ 4.0168,  4.9544,  6.8214,  7.8899,  5.4373, 17.9497, 14.6543,  5.9889,
         11.6812,  1.2434],
        [ 0.3795,  8.5752,  1.5612,  5.1914,  7.7736,  4.3689,  1.2588,  5.6496,
          0.5023,  2.2729],
        [ 4.5504, 1

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)
译者注：没弄懂题目

In [20]:
# 原题答案
# 作者: Nicolas Rougier

Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[2 9 8 3 1 5 9 6 5 7]
 [5 1 1 2 2 8 4 6 0 4]
 [5 0 5 7 1 6 7 6 4 5]
 [1 7 2 2 6 0 5 9 6 5]
 [3 5 9 8 8 5 1 3 0 6]
 [1 1 3 1 9 0 2 9 6 8]
 [7 4 2 8 7 1 5 2 4 8]
 [8 3 1 8 1 8 8 8 0 9]
 [0 0 3 2 0 4 6 1 2 5]
 [5 5 9 8 2 3 3 5 8 4]]
[[0 0 0 0 0]
 [0 2 9 8 3]
 [0 5 1 1 2]
 [0 5 0 5 7]
 [0 1 7 2 2]]


/Users/bello/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:26: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)
译者注：题同 76，只是将 76 中的一行 3 个元素换成了一行 4 个元素。将 `numpy` 中的 `as_strided`改成 Pytorch 中的 `as_strided` 同样会报错

In [72]:
# 原题答案
# 作者: Stefan van der Walt

Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. 计算一个矩阵的秩 (★★★)

In [24]:
# 作者: Stefan van der Walt
Z = torch.rand((10,10))
U, S, V = torch.svd(Z) # Singular Value Decomposition
rank = torch.sum(S > 1e-10)
print(rank)

tensor(10)


#### 83. 找出一维 Tensor 中的众数?

In [37]:
t = torch.randint(0,10,[20])
print(t)
torch.mode(t)

tensor([9, 0, 1, 1, 0, 7, 6, 5, 7, 8, 5, 4, 0, 1, 3, 6, 3, 7, 1, 5])


torch.return_types.mode(values=tensor(1), indices=tensor(18))

#### 84. 从一个 10x10 的矩阵中，提取出所有的连续 3x3 小矩阵 (★★★)

In [54]:
# 作者：Chris Barker
Z = torch.randint(0,5,(4,4))  #  译者注：为了避免打印出来的 Tensor 太长，占据太多页面位置，故此处改为 4x4
print(Z)
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = torch.as_strided(Z, size=(i, j, n, n), stride=Z.stride() + Z.stride())
print(C)

tensor([[3, 3, 3, 4],
        [2, 0, 0, 4],
        [4, 0, 4, 2],
        [2, 4, 4, 4]])
tensor([[[[3, 3, 3],
          [2, 0, 0],
          [4, 0, 4]],

         [[3, 3, 4],
          [0, 0, 4],
          [0, 4, 2]]],


        [[[2, 0, 0],
          [4, 0, 4],
          [2, 4, 4]],

         [[0, 0, 4],
          [0, 4, 2],
          [4, 4, 4]]]])


#### 85. 创建一个 class，输入一个矩阵，将其转换为对称矩阵，同时要确保转换后的对称矩阵任意一个元素修改值后，对称位置元素也要修改 (★★★)

In [107]:
class Symetric:
    def __init__(self, x):
        self.tensor = x + x.T
        
    def __setitem__(self, index, value):
        i,j = index
        self.tensor.__setitem__((i,j), value)
        self.tensor.__setitem__((j,i), value)
    
    def __repr__(self):
        return self.tensor.__repr__()

t = Symetric(torch.arange(16).view((4,4)))
print(t)
t[2,3] = 42
print(t)

tensor([[ 0,  5, 10, 15],
        [ 5, 10, 15, 20],
        [10, 15, 20, 25],
        [15, 20, 25, 30]])
tensor([[ 0,  5, 10, 15],
        [ 5, 10, 15, 20],
        [10, 15, 20, 42],
        [15, 20, 42, 30]])


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)
译者注：题目似乎没写全。题目看起来似乎和那 p 个 vectors 没有关联……

#### 87. 给定一个 16x16 矩阵，如何计算每个子 4x4 矩阵的和? (★★★)
译者注：原题答案使用了 `np.add.reduceat`，Pytorch 没有对应函数

In [131]:
# 作者: Robert Kern

Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

tensor([[[2., 2.],
         [2., 2.]],

        [[2., 2.],
         [2., 2.]]])

#### 88. 使用 Tensor 实现生命游戏（Game of Life）(★★★)
译者注：生命游戏见 https://zh.wikipedia.org/wiki/%E5%BA%B7%E5%A8%81%E7%94%9F%E5%91%BD%E6%B8%B8%E6%88%8F

In [134]:
# 原题答案
# 作者: Nicolas Rougier

def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): 
    Z = iterate(Z)
#     print(Z) 

#### 89. 获取一个 Tensor 中前 n 大的数字 (★★★)

In [138]:
Z = torch.rand(10000)
n = 3
Z.topk(n)

torch.return_types.topk(values=tensor([0.9998, 0.9998, 0.9995]), indices=tensor([2612, 7883, 8855]))

#### 90. 给定任意数量的向量，计算所有向量的笛卡儿积(★★★)

In [149]:
# 原题答案
# 作者: Stefan Van der Walt

def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★)
译者注：使用了 numpy 特有的数据结构 record array。跳过

#### 92. 给定一个长向量 Z，用 3 种方法计算 Z 的 3 次方 (★★★)

In [152]:
x = torch.rand(int(5e7))

%timeit torch.pow(x,3)
%timeit x*x*x
%timeit torch.einsum('i,i,i->i',x,x,x)

146 ms ± 4.19 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
312 ms ± 8.61 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
296 ms ± 4.74 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


#### 93. 给定两个 Tensor A 和 B，尺寸分别为 (8,3) 和 (2,2)。找出 A 中的哪些行包含 B 中所有行的元素。 (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)