# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
# %run initialise.py

#### 1. 导入 PyTorch (★☆☆)

In [1]:
import torch

#### 2. 显示 PyTorch 当前版本 (★☆☆)

In [6]:
print(torch.__version__)

1.4.0


#### 3. 创建一个长度为 10，每个元素值都为 0 的一维 Tensor (★☆☆)

In [9]:
torch.zeros([10])

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. 计算任意 Tensor 的内存占用 (★☆☆)

In [16]:
t = torch.zeros([10,3])
print('%d bytes' % (t.element_size() * t.nelement()))

120 bytes


#### 5. 如何通过命令行获取 PyTorch 函数的帮助文档 (★☆☆)
该问题目前似乎无解。

#### 6. 创建一个长度为 10 的一维 Tensor，除了第五个元素是 1 外，其他元素都是 0(★☆☆)

In [20]:
t = torch.zeros([10])
t[4] = 1
t

tensor([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. 创建一个元素值依次为 10 到 49 的一维 Tensor(★☆☆)

In [21]:
torch.arange(10, 50)

tensor([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
        28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45,
        46, 47, 48, 49])

#### 8. 将一个一维 Tensor 翻转（`[1,2,3]` 变为 `[3,2,1]`）(★☆☆)

In [24]:
t = torch.arange(10, 20)
t.flip(0)

tensor([19, 18, 17, 16, 15, 14, 13, 12, 11, 10])

#### 9. 创建一个 3\*3 的二维 Tensor，值为 0 到 8 (★☆☆)

In [25]:
torch.arange(9).view([3,3])

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

#### 10. 获取 [1,2,0,0,4,0] 中非零元素的下标(★☆☆)

In [29]:
t = torch.Tensor([1,2,0,0,4,0])
t.nonzero()

tensor([[0],
        [1],
        [4]])

#### 11. 创建一个 3\*3 的 单位矩阵（identity matrix） (★☆☆)

In [31]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

#### 12. 创建一个 3x3x3 的随机 Tensor (★☆☆)

In [32]:
torch.rand([3,3,3])

tensor([[[0.4571, 0.9100, 0.3075],
         [0.6895, 0.8641, 0.1467],
         [0.9449, 0.2732, 0.0736]],

        [[0.6917, 0.5758, 0.0902],
         [0.4951, 0.7939, 0.7987],
         [0.5582, 0.1879, 0.1680]],

        [[0.0039, 0.4900, 0.6417],
         [0.9679, 0.5064, 0.1257],
         [0.2158, 0.1603, 0.6950]]])

#### 13. 创建一个 10x10 的随机 Tensor，并找出其中的最大值和最小值(★☆☆)

In [36]:
t = torch.rand([10, 10])
print(t.max())
print(t.min())

tensor(0.9972)
tensor(0.0151)


#### 14. 创建一个长度为 30 的随机一维 Tensor，并计算平均值(★☆☆)

In [37]:
t = torch.rand([30])
t.mean()

tensor(0.5445)

#### 15. 创建一个二维 Tensor，最外围元素是 1，内部元素都是 0 (★☆☆)

In [43]:
t = torch.ones([4,3])
t[1:-1,1:-1] = 0
t

tensor([[1., 1., 1.],
        [1., 0., 1.],
        [1., 0., 1.],
        [1., 1., 1.]])

#### 16. 对一个已有 Tensor 外围添加一圈 0 (★☆☆)

In [50]:
t = torch.ones([2,2])
torch.nn.functional.pad(t, (1,1,1,1), mode='constant', value=0)

tensor([[0., 0., 0., 0.],
        [0., 1., 1., 0.],
        [0., 1., 1., 0.],
        [0., 0., 0., 0.]])

#### 17. 以下代码的运行结果是什么？ (★☆☆)
```python
0 * torch.Tensor([float('NaN')])
torch.Tensor([float('NaN')]) == torch.Tensor([float('NaN')])
torch.Tensor([float('Inf')]) > torch.Tensor([float('NaN')])
torch.Tensor([float('NaN')]) - torch.Tensor([float('NaN')])
torch.Tensor([float('NaN')]) in set([torch.Tensor([float('NaN')])])
0.3 == 3 * 0.1
```

In [57]:
print(0 * torch.Tensor([float('NaN')]))
print(torch.Tensor([float('NaN')]) == torch.Tensor([float('NaN')]))
print(torch.Tensor([float('Inf')]) > torch.Tensor([float('NaN')]))
print(torch.Tensor([float('NaN')]) - torch.Tensor([float('NaN')]))
print(torch.Tensor([float('NaN')]) in set([torch.Tensor([float('NaN')])]))
print(0.3 == 3 * 0.1)

tensor([nan])
tensor([False])
tensor([False])
tensor([nan])
False
False


#### 18. 创建一个 5x5 的矩阵，对角线正下方元素是 1,2,3,4 (★☆☆)

In [61]:
below_diagonal = torch.Tensor([1,2,3,4])
torch.diag(below_diagonal, diagonal=-1)

tensor([[0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0.],
        [0., 2., 0., 0., 0.],
        [0., 0., 3., 0., 0.],
        [0., 0., 0., 4., 0.]])

#### 19. 创建一个 8x8 矩阵，元素值为 0，1 交替出现（类似国际象棋棋盘样式，黑色对应 0，白色对应 1） (★☆☆)

In [62]:
t = torch.zeros((8,8),dtype=int)
t[1::2,::2] = 1
t[::2,1::2] = 1
print(t)

tensor([[0, 1, 0, 1, 0, 1, 0, 1],
        [1, 0, 1, 0, 1, 0, 1, 0],
        [0, 1, 0, 1, 0, 1, 0, 1],
        [1, 0, 1, 0, 1, 0, 1, 0],
        [0, 1, 0, 1, 0, 1, 0, 1],
        [1, 0, 1, 0, 1, 0, 1, 0],
        [0, 1, 0, 1, 0, 1, 0, 1],
        [1, 0, 1, 0, 1, 0, 1, 0]])


#### 20. 一个尺寸为 (6,7,8) 的 Tensor，第 100 个元素的索引（index）是多少？返回的答案应符合 (x,y,z) 格式。
提示：原问题答案使用了 numpy 中的 unravel_index 函数。PyTorch 中暂时没有对应函数，所以需要自己写代码计算。

In [64]:
# 这个函数来自 https://discuss.pytorch.org/t/how-to-do-a-unravel-index-in-pytorch-just-like-in-numpy/12987/3
def unravel_index(index, shape):
    out = []
    for dim in reversed(shape):
        out.append(index % dim)
        index = index // dim
    return tuple(reversed(out))

print(unravel_index(99,(6,7,8)))

(1, 5, 3)


#### 21. 使用 repeat 函数创建一个 8\*8 矩阵，元素值为 0，1 交替出现（类似国际象棋棋盘样式，黑色对应 0，白色对应 1）  (★☆☆)

In [66]:
t = torch.Tensor([[0, 1],
                  [1, 0]])
t.repeat([4, 4])

tensor([[0., 1., 0., 1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1., 0., 1., 0.],
        [0., 1., 0., 1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1., 0., 1., 0.],
        [0., 1., 0., 1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1., 0., 1., 0.],
        [0., 1., 0., 1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 22. 标准化（Normalize）一个 5x5 的随机矩阵 (★☆☆)

In [67]:
t = torch.rand([5,5])
(t - t.mean()) / t.std()

tensor([[-0.0875,  1.9685,  1.0108, -0.9139,  1.0777],
        [ 2.0870,  0.5749, -0.5608, -0.1901, -0.9294],
        [-0.9930, -0.9583, -0.8430,  0.0052,  0.0151],
        [-0.7586, -0.9865,  1.6169, -0.5803, -0.0355],
        [-0.3776, -0.9976,  0.0985,  1.5293, -0.7717]])

#### 23. 创建一个自定义数据结构，使用 4 个无符号字节定义颜色。
原文：Create a custom dtype that describes a color as four unsigned bytes (RGBA)

没太明白题目……

#### 24. 将一个 5x3 矩阵乘以一个 3x2 矩阵(★☆☆)

In [161]:
a = torch.ones([5,3])
b = torch.ones([3,2])
torch.mm(a,b)

tensor([[3., 3.],
        [3., 3.],
        [3., 3.],
        [3., 3.],
        [3., 3.]])

#### 25. 给定一个一维 Tensor，将其中值在 3-8 之间（不包含 3 和 8）的元素取负（不创建新 Tensor） (★☆☆)

In [75]:
t = torch.arange(10)
t[(3<t) & (t<8)] *= -1
t

tensor([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9])

#### 26.以下代码的输出值是什么？ (★☆☆)
```python
# 作者: Jake VanderPlas

print(sum(range(5),-1))
from torch import *
print(sum(range(5),-1))
```

In [87]:
print(sum(range(5),-1))
def test():
    from torch import sum
    print(sum(torch.arange(5), -1))
test()

9
tensor(10)


#### 27. 给定一个整数向量 Z, 以下哪些式子是合法的? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [98]:
# 被注释掉的都不合法
Z = torch.Tensor([1, 2]).type(torch.int)


Z**Z
# 2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
# Z<Z>Z

tensor([1, 2], dtype=torch.int32)

#### 28. 以下表达式的计算结果分别是什么?
```python
torch.Tensor(0) / torch.Tensor(0)
torch.Tensor(0) // torch.Tensor(0)
torch.Tensor([float('NaN')]).type(torch.int).type(torch.float)
```

In [105]:
print(torch.Tensor(0) / torch.Tensor(0))
print(torch.Tensor(0) // torch.Tensor(0))
print(torch.Tensor([float('NaN')]).type(torch.int).type(torch.float))

tensor([])
tensor([])
tensor([-2.1475e+09])


#### 29. 将 float 类型的 Tensor 中元素进位转换为整数 (★☆☆)
译者注：这里的 "进位" 原文是 round away from zero，即 3.2 => 4，-3.2=> -4。可参考 https://en.wikipedia.org/wiki/Rounding

In [112]:
t = torch.randn([2,3]) * 3
print(t)

torch.mul(torch.sign(t), torch.ceil(torch.abs(t)))

tensor([[-5.5260, -3.0378,  1.9262],
        [-1.8656, -3.4310,  2.9551]])


tensor([[-6., -4.,  2.],
        [-2., -4.,  3.]])

#### 30. 找出两个一维 Tensor 中都出现的元素 (★☆☆)
译者注：numpy 可以使用 intersect1d 函数，但 PyTorch 暂无对应函数。简单的处理方法就是转成 numpy array 后使用 intersect1d。

In [114]:
# 原题答案
import numpy as np
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(Z1)
print(Z2)
print(np.intersect1d(Z1,Z2))

[6 1 8 3 9 9 7 8 6 3]
[2 8 6 9 0 7 1 4 4 2]
[1 6 7 8 9]


#### 31. 如何忽略所有的 PyTorch 警告（warnings） (不建议这么做)? (★☆☆)
译者注：numpy 可直接使用 seterr 方法忽略警告，但是 PyTorch 没有内置的相关设置。但是 PyTorch 的所有警告都是使用了 Python 中内置的 warnings，因此可以直接使用 Python 对 warnings 的操作

In [ ]:
import warnings
warnings.filterwarnings("ignore")

#### 32. 以下表达式的值为真吗？ (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

PyTorch 中没有对应 Numpy 的 emath 的模块

In [115]:
np.sqrt(-1) == np.emath.sqrt(-1)

/Users/bello/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

#### 33. 如何获取昨天、今天、明天的日期？ (★☆☆)
译者注：PyTorch 中没有关于日期的模块。

In [116]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')

#### 34. 如何获取 2016 年 7 月的每一天日期? (★★☆)
译者注：PyTorch 中没有关于日期的模块。

In [117]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. 在不复制值的情况下做原地计算 ((A+B)*(-A/2))(★★☆)
译者注：计算过程中的值只能保存在 A/B 中，不能创建新的 Tensor

In [125]:
A = torch.ones(3)*1
B = torch.ones(3)*2
torch.add(A, B, out=B)
torch.div(A, 2, out=A)
torch.neg_(A)
torch.mul(A, B, out=B)
B

tensor([-1.5000, -1.5000, -1.5000])

#### 36. 用 5 种不同的方法提取随机 Tensor 中每个元素的整数部分 (★★☆)

In [127]:
Z = torch.rand([2,2]) * 5
print(Z)


print(Z - Z%1)
print(torch.floor(Z))
print(torch.ceil(Z)-1)
print(Z.type(torch.int))
print(torch.trunc(Z))

tensor([[3.8478, 3.4894],
        [2.3379, 2.6399]])
tensor([[3., 3.],
        [2., 2.]])
tensor([[3., 3.],
        [2., 2.]])
tensor([[3., 3.],
        [2., 2.]])
tensor([[3, 3],
        [2, 2]], dtype=torch.int32)
tensor([[3., 3.],
        [2., 2.]])


#### 37. 创建一个 5x5 矩阵，每一行的值是 0-4(★★☆)

In [130]:
torch.arange(5).repeat([5,1])

tensor([[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]])

#### 38. 创建一个生成器函数，用于生成 10 个整数，并用这个生成器函数创建一个一维 Tensor(★☆☆)
译者注:numpy 支持从生成器中创建 array，但 PyTorch 不支持。可以先将这个生成器转换成 numpy array，再转换为 PyTorch tensor

In [133]:
def g():
    yield from range(10)
torch.from_numpy(np.fromiter(g(), dtype=np.int))

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 39. 创建一个长度为 10 的向量，每个元素的值在 0-1 之间（不包括 0 和 1）(★★☆)

In [135]:
torch.linspace(0, 1, steps=12)[1:-1]

tensor([0.0909, 0.1818, 0.2727, 0.3636, 0.4545, 0.5455, 0.6364, 0.7273, 0.8182,
        0.9091])

#### 40. 创建一个长度为 10 的随机向量，并排序(★★☆)

In [137]:
torch.sort(torch.rand([10]))

torch.return_types.sort(values=tensor([0.1705, 0.2274, 0.2365, 0.2937, 0.3066, 0.5960, 0.6386, 0.6657, 0.8584,
        0.9452]), indices=tensor([8, 7, 6, 1, 3, 0, 5, 9, 2, 4]))

#### 41. 对一个小向量求和时，如何计算才能比使用 np.sum 更快？(★★☆)
译者注：在 numpy 中，可以使用 np.add.reduce，在小向量上计算速度快于np.sum。但 PyTorch 似乎没有对应的方法，经测试，对 `torch.arange(10)` 进行求和时，torch.sum 仍然快于 np.add.reduce

In [151]:
# 原题答案
Z = np.arange(10)
np.add.reduce(Z)

45

#### 42. 给定两个随机 Tensor A 和 B，判断是否相等 (★★☆)

In [160]:
# 检查值是否精确相等
print(torch.equal(torch.Tensor([1.1, 2.1]), torch.Tensor([1, 2])))

# 检查值相等时允许一定误差
print(torch.allclose(torch.Tensor([1.1, 2.1]), torch.Tensor([1, 2]), atol=0.2))

False
True


#### 43. 将 Tensor 转变为只读(★★☆)
译者注：numpy 可以对数组定义 writeable 属性，但 PyTorch 貌似不支持

In [ ]:
# 原题答案
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

#### 44. 一个随机 10x2 矩阵，每一行表示一个笛卡尔坐标，将其转换为对应的极坐标值 (★★☆)

In [180]:
t = torch.rand([10, 2])
X = t[:,0]
Y = t[:,1]
R = torch.sqrt(X**2+Y**2)
T = torch.atan(Y/X)
torch.stack([R,T], dim=1)

tensor([[0.4773, 0.7567],
        [0.5372, 1.3212],
        [0.3995, 1.0767],
        [0.9242, 0.9264],
        [0.7047, 0.4722],
        [1.1001, 0.7278],
        [1.0369, 1.2394],
        [0.9369, 0.4597],
        [0.7984, 0.7668],
        [0.7370, 0.3414]])

#### 45. 创建一个长度为 10 的随机向量，将其中最大值替换为 0(★★☆)

In [186]:
t = torch.rand(10)
t[torch.argmax(t)] = 0
t

tensor([0.6444, 0.3826, 0.8746, 0.8124, 0.5539, 0.6790, 0.0437, 0.0000, 0.6264,
        0.1880])

#### 46. 在直角坐标轴上 (0,0) 到 (1,1) 区域内放一个 5x5 的网格，创建一个5x5x2 的 Tensor，其值对应网格中每个点的坐标(★★☆)
译者注：原题要求使用 numpy 的 structured array 这个数据结构，PyTorch 疑似没有。故略微修改了题目。

In [196]:
X,Y = torch.meshgrid(torch.linspace(0,1,5),
                     torch.linspace(0,1,5))
torch.stack([X,Y], dim=2)

tensor([[[0.0000, 0.0000],
         [0.0000, 0.2500],
         [0.0000, 0.5000],
         [0.0000, 0.7500],
         [0.0000, 1.0000]],

        [[0.2500, 0.0000],
         [0.2500, 0.2500],
         [0.2500, 0.5000],
         [0.2500, 0.7500],
         [0.2500, 1.0000]],

        [[0.5000, 0.0000],
         [0.5000, 0.2500],
         [0.5000, 0.5000],
         [0.5000, 0.7500],
         [0.5000, 1.0000]],

        [[0.7500, 0.0000],
         [0.7500, 0.2500],
         [0.7500, 0.5000],
         [0.7500, 0.7500],
         [0.7500, 1.0000]],

        [[1.0000, 0.0000],
         [1.0000, 0.2500],
         [1.0000, 0.5000],
         [1.0000, 0.7500],
         [1.0000, 1.0000]]])

#### 47. 给定两个向量 X,Y，创建一个柯西矩阵 C（Cij =1/(xi - yj)）

In [200]:
x = torch.Tensor([1,2,3])
y = torch.Tensor([4,8,12, 15])
torch.div(1, x.view([-1,1]) - y)

tensor([[-0.3333, -0.1429, -0.0909, -0.0714],
        [-0.5000, -0.1667, -0.1000, -0.0769],
        [-1.0000, -0.2000, -0.1111, -0.0833]])

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [ ]:
AN BB


#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)