# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
# %run initialise.py

#### 1. 导入 PyTorch (★☆☆)

In [1]:
import torch

#### 2. 显示 PyTorch 当前版本 (★☆☆)

In [6]:
print(torch.__version__)

1.4.0


#### 3. 创建一个长度为 10，每个元素值都为 0 的一维 Tensor (★☆☆)

In [9]:
torch.zeros([10])

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. 计算任意 Tensor 的内存占用 (★☆☆)

In [16]:
t = torch.zeros([10,3])
print('%d bytes' % (t.element_size() * t.nelement()))

120 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [18]:
torch.des

AttributeError: module 'torch' has no attribute 'info'

#### 6. 创建一个长度为 10 的一维 Tensor，除了第五个元素是 1 外，其他元素都是 0(★☆☆)

In [20]:
t = torch.zeros([10])
t[4] = 1
t

tensor([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. 创建一个元素值依次为 10 到 49 的一维 Tensor(★☆☆)

In [21]:
torch.arange(10, 50)

tensor([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
        28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45,
        46, 47, 48, 49])

#### 8. 将一个一维 Tensor 翻转（`[1,2,3]` 变为 `[3,2,1]`）(★☆☆)

In [24]:
t = torch.arange(10, 20)
t.flip(0)

tensor([19, 18, 17, 16, 15, 14, 13, 12, 11, 10])

#### 9. 创建一个 3\*3 的二维 Tensor，值为 0 到 8 (★☆☆)

In [25]:
torch.arange(9).view([3,3])

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

#### 10. 获取 [1,2,0,0,4,0] 中非零元素的下标(★☆☆)

In [29]:
t = torch.Tensor([1,2,0,0,4,0])
t.nonzero()

tensor([[0],
        [1],
        [4]])

#### 11. 创建一个 3\*3 的 单位矩阵（identity matrix） (★☆☆)

In [31]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

#### 12. 创建一个 3x3x3 的随机 Tensor (★☆☆)

In [32]:
torch.rand([3,3,3])

tensor([[[0.4571, 0.9100, 0.3075],
         [0.6895, 0.8641, 0.1467],
         [0.9449, 0.2732, 0.0736]],

        [[0.6917, 0.5758, 0.0902],
         [0.4951, 0.7939, 0.7987],
         [0.5582, 0.1879, 0.1680]],

        [[0.0039, 0.4900, 0.6417],
         [0.9679, 0.5064, 0.1257],
         [0.2158, 0.1603, 0.6950]]])

#### 13. 创建一个 10x10 的随机 Tensor 10x10，并找出其中的最大值和最小值(★☆☆)

In [36]:
t = torch.rand([10, 10])
print(t.max())
print(t.min())

tensor(0.9972)
tensor(0.0151)


#### 14. 创建一个长度为 30 的随机一维 Tensor，并计算平均值(★☆☆)

In [37]:
t = torch.rand([30])
t.mean()

tensor(0.5445)

#### 15. 创建一个二维 Tensor，最外围元素是 1，内部元素都是 0 (★☆☆)

In [43]:
t = torch.ones([4,3])
t[1:-1,1:-1] = 0
t

tensor([[1., 1., 1.],
        [1., 0., 1.],
        [1., 0., 1.],
        [1., 1., 1.]])

#### 16. 对一个已有 Tensor 外围添加一圈 0 (★☆☆)

In [50]:
t = torch.ones([2,2])
torch.nn.functional.pad(t, (1,1,1,1), mode='constant', value=0)

tensor([[0., 0., 0., 0.],
        [0., 1., 1., 0.],
        [0., 1., 1., 0.],
        [0., 0., 0., 0.]])

#### 17. 以下代码的运行结果是什么？ (★☆☆)
```python
0 * torch.Tensor([float('NaN')])
torch.Tensor([float('NaN')]) == torch.Tensor([float('NaN')])
torch.Tensor([float('Inf')]) > torch.Tensor([float('NaN')])
torch.Tensor([float('NaN')]) - torch.Tensor([float('NaN')])
torch.Tensor([float('NaN')]) in set([torch.Tensor([float('NaN')])])
0.3 == 3 * 0.1
```

In [57]:
print(0 * torch.Tensor([float('NaN')]))
print(torch.Tensor([float('NaN')]) == torch.Tensor([float('NaN')]))
print(torch.Tensor([float('Inf')]) > torch.Tensor([float('NaN')]))
print(torch.Tensor([float('NaN')]) - torch.Tensor([float('NaN')]))
print(torch.Tensor([float('NaN')]) in set([torch.Tensor([float('NaN')])]))
print(0.3 == 3 * 0.1)

tensor([nan])
tensor([False])
tensor([False])
tensor([nan])
False
False


#### 18. 创建一个 5x5 的矩阵，对角线正下方元素是 1,2,3,4 (★☆☆)

In [61]:
below_diagonal = torch.Tensor([1,2,3,4])
torch.diag(below_diagonal, diagonal=-1)

tensor([[0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0.],
        [0., 2., 0., 0., 0.],
        [0., 0., 3., 0., 0.],
        [0., 0., 0., 4., 0.]])

#### 19. 创建一个 8x8 矩阵，元素值为 0，1 交替出现（类似国际象棋棋盘样式，黑色对应 0，白色对应 1） (★☆☆)

In [62]:
t = torch.zeros((8,8),dtype=int)
t[1::2,::2] = 1
t[::2,1::2] = 1
print(t)

tensor([[0, 1, 0, 1, 0, 1, 0, 1],
        [1, 0, 1, 0, 1, 0, 1, 0],
        [0, 1, 0, 1, 0, 1, 0, 1],
        [1, 0, 1, 0, 1, 0, 1, 0],
        [0, 1, 0, 1, 0, 1, 0, 1],
        [1, 0, 1, 0, 1, 0, 1, 0],
        [0, 1, 0, 1, 0, 1, 0, 1],
        [1, 0, 1, 0, 1, 0, 1, 0]])


#### 20. 一个尺寸为 (6,7,8) 的 Tensor，第 100 个元素的索引（index）是多少?

In [63]:
t.index

AttributeError: 'Tensor' object has no attribute 'index'

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

#### 22. Normalize a 5x5 random matrix (★☆☆)

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 29. How to round away from zero a float array ? (★☆☆)

#### 30. How to find common values between two arrays? (★☆☆)

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)